apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: long-job
        image: python
        command: ["python"]
        args: ["-c", "import time; print('starting'); time.sleep(30); print('done')"]
      restartPolicy: Never
      #一共有三种值: Always, OnFailure, Never
  backoffLimit: 3 #如果失败，最多尝试多少次
